### ISSUE TITLE
Motion executor

### ISSUE THREAD

**Issue by darko31** [bstaletic/eurobot2k17#18]
Propose and implement:
- tracking current position and status
- structure features
- corner cases
- enemy detection
- pathfinding, API

**Comment by bstaletic** [comment]
I think this should be split into smaller pieces. At the very least pathfinding could be considered a "utility" or "helper". Enemy detection could be a different executor, but it may not need to send messages to motion executor?

My idea of this tends to look like what Memristor used in the previous two years.

**Comment by to92me** [comment]
> At the very least pathfinding could be considered a "utility" or "helper".

path finding is util but it is used in motion and motion with path-finding must have a add-on on API. Functions: turn on pf, turn off pf, go there with or without pf and etc... 

>  Enemy detection could be a different executor, but it may not need to send messages to motion executor?

In our case every sensor is one interrupt and purpose of enemy detector executor would be accept interrupt send flag to motion. There is no real job for enemy detector executor. 

> My idea of this tends to look like what Memristor used in the previous two years. 

Hmmm I am quite familiar with code, because I wrote it :P

**Comment by bstaletic** [comment]
>path finding is util but it is used in motion and motion with path-finding must have a add-on on API.

Correct, but what I wanted to say was that we shouldn't just put everything in motion executor. Interfacing path finding as a utility, to me, seems like a cleaner approach.

>There is no real job for enemy detector executor.

I kinda forgot Memristor used modbus to communicate with everything, even "simple" digital inputs like these.

As far as familiarity with the Memristor's code goes, I'd say I'm quite familiar with this part of it as well. Though my tool for refactoring looked less like a scalpel and more like a chainsaw at one point. The chainsaw fixed a problbem with detection, but disallowed path finding. :D
