### ISSUE TITLE
Sensors driver

### ISSUE THREAD

**Issue by darko31** [bstaletic/eurobot2k17#19]
Propose API and implement driver:
- "debouncing" (not really debouncing, but ignoring quick detection cases)
- front, left, right and back sensors, and possibly some internal sensors

**Comment by bstaletic** [comment]
As far as "debouncing" goes, it would be easier to read the sensor three times in a row or something along those lines. I don't like this approach as it makes us poll each sensor instead of relying on external interrupts.

How about triggering a timer on the rising edge of the sensor inside a timer, having timer tick for 3ms(?) and all along waiting for a falling edge. If no falling edge is found in those 3ms we have actually detected something important.
This requries much more code than just waiting for a rising edge and stopping no matter what. 

Any other suggestions?

@darko31 don't you think this should be in "basic functionality" milestone?

**Comment by to92me** [comment]
We should wait for hw and see how it works. Those are expensive sensors and probably have more than one level of debouncing.

**Comment by ivar94** [comment]
@darko31 give data sheet pls.

**Comment by ivar94** [comment]
Can we give approximate count how many sensors we will be using?
Suggestion for Enterprise robot:
- 3 front sensors
- 2 or 3 back sensors
- 1 internal sensor

I don't know how may sensors we will get so I'm trying to keep the count minimum.
I added one internal sensor cause i think it will be necessary for us/our robot to know if he is actually pulling in the tube, so he wont waste time.
Any idea how that could work? I was thinking we could get average time robot needs to pull in the tube, and if the internal sensor dose not trigger (cause it will be positioned inside, above the front opening) in half of that time we know that robot missed the tube, or it was moved, abort the process and move to the next tube. We will save a lot of precious time.
